import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('雙平台、照片、候選網格與本機範例流程', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'LINE Sticker Studio' })).toBeVisible();
  await expect(page.getByRole('tab')).toHaveCount(7);
  await page.getByRole('button', { name: /Gemini/ }).click();
  await expect(page.getByText(/Gemini · 一份 MD/)).toBeVisible();
  await expect(page.getByText('3×3＝9 格')).toBeVisible();
  await expect(page.getByText('角色題材', { exact: true })).toBeVisible();
  await page.getByLabel('類別').selectOption('plants');
  await page.getByLabel('子項目').selectOption('sunflower');
  await expect(page.getByText(/anthropomorphic sunflower/)).toBeVisible();
  const photoInput = page.locator('.photo-section input[type="file"]');
  await photoInput.setInputFiles({ name: 'me.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+Xw4WAAAAAElFTkSuQmCC', 'base64') });
  await expect(page.getByText('me.png', { exact: true })).toBeVisible();
  await expect(page.getByText('照片模式')).toBeVisible();
  await expect(page.getByText(/me.png as the primary reference/)).toBeVisible();
  await page.getByLabel(/我確認擁有照片使用權/).check();
  const mdDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '下載完整產圖 MD' }).click();
  const mdPath = await (await mdDownload).path();
  expect(mdPath).toBeTruthy();
  const markdown = await readFile(mdPath!, 'utf8');
  expect(markdown).toContain('line-sticker-task/v4');
  expect(markdown).toContain('me.png');
  expect(markdown).toContain('ONLY appearance and identity source');
  expect(markdown).toContain('STOP and ask me to re-upload');
  expect(markdown).not.toContain('taiwan-black-bear');
  expect(markdown).not.toContain('台灣黑熊');
  expect(markdown.toLowerCase()).not.toContain('black bear');
  expect(markdown).not.toContain('"categoryId": "plants"');
  expect(markdown).toContain('3 columns and 3 rows');
  const backupDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '儲存專案' }).click();
  const backupPath = await (await backupDownload).path();
  expect(backupPath).toBeTruthy();
  await page.reload();
  await page.locator('header input[type="file"]').setInputFiles(backupPath!);
  await expect(page.getByText('me.png', { exact: true })).toBeVisible();
  await page.locator('.reference-photo .photo-buttons button').last().click();
  await expect(page.getByLabel('子項目')).toHaveValue('sunflower');
  await page.getByRole('tab', { name: /大貼圖/ }).click();
  await expect(page.getByText(/最大 396×660/)).toBeVisible();
  await page.getByRole('button', { name: '載入範例' }).click();
  await expect(page.getByText('已切割 9 張')).toBeVisible();
  await expect(page.getByText('候選 9 張 · 入選 8/8')).toBeVisible();
  await page.getByRole('button', { name: '設為入選' }).click();
  await expect(page.getByText('候選 9 張 · 入選 8/8')).toBeVisible();
});
